Repository ros2/rosidl_typesupport_opensplice, pull requests merged in 2018-11, with the labels that each got.

#9 rename dynamic array to sequence
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
Labels: in review

#8 Allow generated IDL files
  rosidl_typesupport_opensplice_c/cmake/rosidl_typesupport_opensplice_c_generate_interfaces.cmake
  rosidl_typesupport_opensplice_cpp/cmake/rosidl_typesupport_opensplice_cpp_generate_interfaces.cmake
Labels: in progress

#10 Replace more srv with @(subfolder)
  rosidl_typesupport_opensplice_c/resource/srv__type_support_c.cpp.em
Labels: bug, in review

#14 suppress warning on Windows
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/impl/error_checking.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/requester.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/responder.hpp
Labels: in review

#12 add opensplice support for cdr serialization
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/message_type_support.h
  rosidl_typesupport_opensplice_cpp/resource/msg__rosidl_typesupport_opensplice_cpp.hpp.em
  rosidl_typesupport_opensplice_cpp/resource/msg__type_support.cpp.em
Labels: in review
