Repository ros2/rosidl_typesupport_opensplice, pull requests merged in 2019-05, with the labels that each got.

#27 add WString mapping to String
  rosidl_typesupport_opensplice_c/resource/idl__dds_opensplice__type_support.c.em
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/idl__dds_opensplice__type_support.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp/rosidl_generator_dds_idl_extension.py
Labels: enhancement, in review

#29 fix codecvt use on Windows
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/msg__type_support.cpp.em
Labels: bug, in review

#28 Combine package name with namespace in message and service type support structs
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_opensplice_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/message_type_support.h
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/service_type_support.h
  rosidl_typesupport_opensplice_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/srv__type_support.cpp.em
Labels: in progress
